# Change these first
owner: maxysoft # Your GitHub organization or username, where this repository lives
repo: taco-status # The name of this repository

sites:
  - name: WAX RPC API
    url: https://api-wax.tacocrypto.io/v1/chain/get_info
  - name: Hyperion
    url: https://api-wax.tacocrypto.io/hyperion/v2/health
  - name: Atomic
    url: https://https://atomic-wax.tacocrypto.io/health
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /taco-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**TacoStudios** status page."
  introMessage: TacoStudios Services status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
